security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
            
    providers:
        user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    role_hierarchy:
    #    ROLE_ELEVE:       ROLE_USER
    #    ROLE_CONSEILLER:  ROLE_ELEVE
        ROLE_ADMIN: ROLE_CONSEILLER


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            logout :
                path : logout
                target: /
            
            provider : user_provider
            
            form_login :
                login_path : connexion
                check_path : connexion
                username_parameter: _username
                password_parameter: _password
                default_target_path: home
                failure_path: connexion
                
            access_denied_handler: App\Security\AccessDeniedHandler
        
      

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/conseiller, roles: ROLE_CONSEILLER }
         - { path: ^/forum*, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/, roles: PUBLIC_ACCESS }
