<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'avatar' => [parent::class, 'avatar', null],
        "\0".parent::class."\0".'cin' => [parent::class, 'cin', null],
        "\0".parent::class."\0".'confirm_mdp' => [parent::class, 'confirm_mdp', null],
        "\0".parent::class."\0".'dateInscription' => [parent::class, 'dateInscription', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'idUser' => [parent::class, 'idUser', null],
        "\0".parent::class."\0".'mdp' => [parent::class, 'mdp', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null],
        'avatar' => [parent::class, 'avatar', null],
        'cin' => [parent::class, 'cin', null],
        'confirm_mdp' => [parent::class, 'confirm_mdp', null],
        'dateInscription' => [parent::class, 'dateInscription', null],
        'email' => [parent::class, 'email', null],
        'idUser' => [parent::class, 'idUser', null],
        'mdp' => [parent::class, 'mdp', null],
        'nom' => [parent::class, 'nom', null],
        'prenom' => [parent::class, 'prenom', null],
        'role' => [parent::class, 'role', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'confirm_mdp' => true,
            "\0".parent::class."\0".'idUser' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
