<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ5BRA5x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ5BRA5x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ5BRA5x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ5BRA5x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ5BRA5x\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z5BRA5x',
    'container.build_id' => '653e6c99',
    'container.build_time' => 1685817392,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ5BRA5x');
